use futures::{FutureExt, StreamExt, TryStreamExt};
use reqwest::Client;
use scraper::{Html, Selector};
use tokio::io::{self, AsyncBufReadExt, BufReader};
use url::Url;

const CONCURRENCY: usize = 200;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = Client::builder().user_agent("logo-crawler/0.1").build()?;
    let stdin = BufReader::new(io::stdin());
    let lines = tokio_stream::wrappers::LinesStream::new(stdin.lines());

    // do I need a handle to stdout, or can I just use println?
    // let mut writer = io::stdout();
    println!("domain,logo url");

    let mut stream = lines
        .map_ok(|domain| normalize_domain(&domain))
        .try_filter(|d| futures::future::ready(!d.is_empty()))
        .map(|res| match res {
            Ok(domain) => fetch_logo(&client, domain).boxed(),
            Err(_) => async { ("".to_string(), None) }.boxed(),
        })
        .buffer_unordered(CONCURRENCY);

    while let Some(result) = stream.next().await {
        let (domain, logo) = result;
        if let Some(l) = logo {
            println!("{domain},{l}");
        } else {
            println!("{domain},")
        }
    }

    Ok(())
}

fn normalize_domain(input: &str) -> String {
    let s = input.trim();

    if s.starts_with("http://") || s.starts_with("https://") {
        s.to_string()
    } else {
        format!("https://{}", s)
    }
}

async fn fetch_logo(client: &Client, domain: String) -> (String, Option<String>) {
    // need to understand what kind of error I want here
    match try_fetch_logo(client, &domain).await {
        Ok(url) => (domain, url),
        Err(_) => (domain, None),
    }
}

async fn try_fetch_logo(
    client: &Client,
    domain: &str,
) -> Result<Option<String>, Box<dyn std::error::Error>> {
    let resp = client.get(domain).send().await?;
    let base = resp.url().clone();
    let body = resp.text().await?;

    Ok(extract_logo(&body, &base))
}

// I assume the logo will be on the same server?
fn extract_logo(html: &str, base: &Url) -> Option<String> {
    let document = Html::parse_document(html);

    // these selectors were generated by AI, cause I don't know shit about where modern
    // sites store their logos
    let og = Selector::parse(r#"meta[property="og:image"]"#).unwrap();
    let twitter = Selector::parse(r#"meta[name="twitter:image"]"#).unwrap();
    let icon = Selector::parse(r#"link[rel~="icon"]"#).unwrap();
    let apple = Selector::parse(r#"link[rel="apple-touch-icon"]"#).unwrap();
    let img_logo = Selector::parse(r#"img[src*="logo"]"#).unwrap();

    for sel in [&icon, &apple] {
        if let Some(el) = document.select(sel).next() {
            if let Some(url) = el.value().attr("href") {
                return base.join(url).ok().map(|u| u.to_string());
            }
        }
    }

    for sel in [&og, &twitter] {
        if let Some(el) = document.select(sel).next() {
            if let Some(url) = el.value().attr("content") {
                return base.join(url).ok().map(|u| u.to_string());
            }
        }
    }

    if let Some(el) = document.select(&img_logo).next() {
        if let Some(url) = el.value().attr("src") {
            return base.join(url).ok().map(|u| u.to_string());
        }
    }

    None
}
